FROM python:alpine

WORKDIR /app

RUN chown nobody:nogroup /app \
	&& apk add --no-cache --virtual .build-deps gcc build-base libffi-dev libretls-dev

ADD requirements.txt .
RUN pip install -r requirements.txt \
	&& apk del .build-deps

COPY --chown=nobody:nogroup . .
COPY --chown=nobody:nogroup config.example.yml config.yml
USER nobody

ENTRYPOINT [ "python", "deezer.py" ]
