FROM python:alpine

WORKDIR /app

ADD requirements.txt .

RUN apk add --no-cache --virtual .build-deps gcc build-base libffi-dev libretls-dev cargo && \
    pip install -r requirements.txt && \
	apk del .build-deps && \
	chown -R nobody:nogroup /app

COPY --chown=nobody:nogroup . .
COPY --chown=nobody:nogroup config.example.yml config.yml

USER nobody

ENTRYPOINT [ "python", "tidal.py" ]
