apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "musicsearchbot.fullname" . }}
  labels:
    {{ include "musicsearchbot.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envVars | nindent 2 }}
