replicaCount: 1

image:
  repository: ghcr.io/juniorjpdj/musicsearchbot-deezer
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL

resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

envVars: {}

secretEnvVars: {}

nodeSelector: {}

tolerations: []

affinity: {}
