name: Docker build

on:
  push:
    branches: 
      - master
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/386
          - linux/arm/v7
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare variables
        id: vars
        run: |
          platform=${{ matrix.platform }}
          echo "platform_pair=${platform//\//-}" >> $GITHUB_OUTPUT
          echo "platform_pair_un=${platform//\//_}" >> $GITHUB_OUTPUT

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract Docker metadata for Deezer
        id: meta-deezer
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-deezer

      - name: Extract Docker metadata for Tidal
        id: meta-tidal
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-tidal

      - name: Extract image without tag from metadata
        id: image
        run: |
          image_deezer=${{ steps.meta-deezer.outputs.tags }}
          image_tidal=${{ steps.meta-tidal.outputs.tags }}
          echo "image_deezer=${image_deezer%%:*}" >> $GITHUB_OUTPUT
          echo "image_tidal=${image_tidal%%:*}" >> $GITHUB_OUTPUT

      - name: Setup buildx mount cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            home-cache
            home-cargo
          key: buildx-mount-cache-${{ steps.vars.outputs.platform_pair }}-${{ github.sha }}
          restore-keys: |
            buildx-mount-cache-${{ steps.vars.outputs.platform_pair }}-

      - name: Inject buildx mount cache into docker
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          cache-map: |
            {
              "home-cache": {
                "target": "/root/.cache",
                "id": "home-cache-${{ matrix.platform }}"
              },
              "home-cargo": {
                "target": "/root/.cargo",
                "id": "home-cargo-${{ matrix.platform }}"
              }
            }

      - name: Build and push Docker image for Deezer
        id: build-and-push-deezer
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: .
          file: deezer.Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          outputs: type=image,"name=${{ steps.image.outputs.image_deezer }}",push-by-digest=true,name-canonical=true,push=true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for Tidal
        id: build-and-push-tidal
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: .
          file: tidal.Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          outputs: type=image,"name=${{ steps.image.outputs.image_tidal }}",push-by-digest=true,name-canonical=true,push=true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Workaround for https://github.com/actions/runner/pull/2477
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests-deezer ${{ runner.temp }}/digests-tidal
          digest="${{ steps.build-and-push-deezer.outputs.digest }}"
          touch "${{ runner.temp }}/digests-deezer/${digest#sha256:}"
          digest="${{ steps.build-and-push-tidal.outputs.digest }}"
          touch "${{ runner.temp }}/digests-tidal/${digest#sha256:}"

      - name: Upload Deezer digest as an artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: digests-deezer-${{ steps.vars.outputs.platform_pair }}
          path: ${{ runner.temp }}/digests-deezer/*
          if-no-files-found: error
          retention-days: 1

      - name: Upload Tidal digest as an artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: digests-tidal-${{ steps.vars.outputs.platform_pair }}
          path: ${{ runner.temp }}/digests-tidal/*
          if-no-files-found: error
          retention-days: 1

    outputs:
      image_deezer: ${{ steps.image.outputs.image_deezer }}
      image_tidal: ${{ steps.image.outputs.image_tidal }}
    # https://github.com/actions/runner/pull/2477 :<
    #   ${{ steps.vars.outputs.platform_pair_un }}_digest: ${{ steps.build-and-push.outputs.digest }}

  merge:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    needs:
      - build
    steps:
      - name: Download Deezer digests
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: ${{ runner.temp }}/digests-deezer
          pattern: digests-deezer-*
          merge-multiple: true

      - name: Download Tidal digests
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: ${{ runner.temp }}/digests-tidal
          pattern: digests-tidal-*
          merge-multiple: true

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for Deezer
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-deezer
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create manifest list and push for Deezer
        working-directory: ${{ runner.temp }}/digests-deezer
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ needs.build.outputs.image_deezer }}@sha256:%s ' *)

      - name: Extract Docker metadata for Tidal
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-tidal
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create manifest list and push for Tidal
        working-directory: ${{ runner.temp }}/digests-tidal
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ needs.build.outputs.image_tidal }}@sha256:%s ' *)
