name: Docker build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '25 15 * * *'
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for Deezer
        id: build-and-push-deezer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.deezer
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:deezer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for Tidal
        id: build-and-push-tidal
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.tidal
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:tidal
          cache-from: type=gha
          cache-to: type=gha,mode=max
